<!DOCTYPE html>
<html lang="en">
<head>@include('partials.head')</head>
<body class="min-h-screen bg-[#f7f7f8] text-zinc-950 dark:bg-zinc-950 dark:text-white">
    <header class="mx-auto flex max-w-7xl items-center justify-between px-6 py-6 lg:px-10"><a href="/" class="flex items-center gap-3"><span class="grid size-9 place-items-center rounded-xl bg-indigo-600 font-bold text-white">W</span><span class="font-semibold">WorkHub</span></a><nav class="flex items-center gap-2">@auth<flux:button :href="route('dashboard')" variant="primary">Open dashboard</flux:button>@else<flux:button :href="route('login')" variant="ghost">Sign in</flux:button><flux:button :href="route('register')" variant="primary">Create account</flux:button>@endauth</nav></header>
    <main class="mx-auto grid max-w-7xl items-center gap-16 px-6 py-20 lg:grid-cols-2 lg:px-10 lg:py-28">
        <div><span class="inline-flex rounded-full border border-indigo-200 bg-indigo-50 px-3 py-1 text-xs font-medium text-indigo-700 dark:border-indigo-900 dark:bg-indigo-950 dark:text-indigo-300">One workspace. Total clarity.</span><h1 class="mt-7 text-5xl font-semibold leading-[1.05] tracking-[-0.045em] sm:text-6xl">Projects and documents, finally in sync.</h1><p class="mt-6 max-w-xl text-lg leading-8 text-zinc-600 dark:text-zinc-400">Plan work, collaborate on documents, manage access, and keep every decision connected to the project that shaped it.</p><div class="mt-9 flex gap-3"><flux:button :href="route('register')" variant="primary" class="px-5 py-3" icon-trailing="arrow-right">Start working</flux:button><flux:button :href="route('login')" class="px-5 py-3">Sign in</flux:button></div></div>
        <div class="relative"><div class="absolute -inset-8 -z-10 rounded-full bg-indigo-300/30 blur-3xl dark:bg-indigo-900/20"></div><div class="rounded-3xl border border-zinc-200 bg-white p-4 shadow-2xl shadow-zinc-950/10 dark:border-zinc-800 dark:bg-zinc-900"><div class="flex items-center gap-2 border-b border-zinc-100 px-2 pb-4 dark:border-zinc-800"><span class="size-2.5 rounded-full bg-red-400"></span><span class="size-2.5 rounded-full bg-amber-400"></span><span class="size-2.5 rounded-full bg-emerald-400"></span></div><div class="grid gap-4 p-3 sm:grid-cols-2">@foreach([['Website Redesign','12 documents','Active'],['Security Readiness','8 documents','Active'],['Q4 Campaign','18 documents','Active'],['Legacy Intranet','24 documents','Archived']] as [$name,$docs,$status])<div class="rounded-2xl border border-zinc-200 p-5 dark:border-zinc-800"><span class="grid size-10 place-items-center rounded-xl bg-indigo-50 text-sm font-semibold text-indigo-700 dark:bg-indigo-950 dark:text-indigo-300">{{ str($name)->substr(0,2)->upper() }}</span><h2 class="mt-5 font-medium">{{ $name }}</h2><div class="mt-2 flex justify-between text-xs text-zinc-500"><span>{{ $docs }}</span><span>{{ $status }}</span></div></div>@endforeach</div></div></div>
    </main>
    @fluxScripts
</body>
</html>
