<div class="max-w-5xl">
    <x-page-header title="Profile" description="Manage your identity, avatar, activity, and active sessions." />
    @if(session('success'))<div class="mb-5 rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{{ session('success') }}</div>@endif
    <div class="grid gap-6 md:grid-cols-2">
        <form wire:submit="save" class="rounded-2xl border border-zinc-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900"><h2 class="font-semibold">Profile details</h2><div class="mt-5 space-y-5"><flux:input wire:model="name" label="Name" /><flux:input value="{{ auth()->user()->email }}" label="Email" disabled /><flux:input wire:model="avatar" type="file" label="Upload avatar" /></div><flux:button type="submit" variant="primary" class="mt-6">Save profile</flux:button></form>
        <form wire:submit="importAvatar" class="h-fit rounded-2xl border border-zinc-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900"><h2 class="font-semibold">Import avatar</h2><p class="mt-1 text-sm text-zinc-500">Use an image hosted on an approved domain.</p><flux:input wire:model="avatarUrl" type="url" label="Image URL" class="mt-5" placeholder="https://images.unsplash.com/…" /><flux:button type="submit" class="mt-6">Import from URL</flux:button></form>
    </div>
    <div class="mt-6 grid gap-6 md:grid-cols-2">
        <section class="rounded-2xl border border-zinc-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900"><h2 class="font-semibold">Active sessions</h2><p class="mt-1 text-sm text-zinc-500">Devices currently signed in to your account.</p><div class="mt-5 divide-y divide-zinc-100 dark:divide-zinc-800">@forelse($sessions as $item)<div class="flex items-center gap-3 py-4"><span class="grid size-9 place-items-center rounded-lg bg-zinc-100 text-zinc-500 dark:bg-zinc-800"><flux:icon.computer-desktop class="size-4" /></span><span class="min-w-0 flex-1"><span class="block truncate text-xs">{{ $item->user_agent ?: 'Unknown device' }}</span><span class="block text-xs text-zinc-400">{{ $item->ip_address ?: 'Unknown IP' }} · {{ \Carbon\Carbon::createFromTimestamp($item->last_activity)->diffForHumans() }}</span></span>@if($item->id === session()->getId())<x-status-badge value="active" />@else<flux:button wire:click="revokeSession('{{ $item->id }}')" size="sm" variant="danger">Sign out</flux:button>@endif</div>@empty<p class="py-6 text-sm text-zinc-500">No database sessions found.</p>@endforelse</div></section>
        <section class="rounded-2xl border border-zinc-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900"><h2 class="font-semibold">Account activity</h2><p class="mt-1 text-sm text-zinc-500">Your latest actions across projects.</p><div class="mt-5 space-y-5">@forelse($activities as $activity)<div class="flex gap-3"><span class="mt-1 size-2 rounded-full bg-indigo-500"></span><span class="min-w-0"><span class="block text-sm">{{ $activity->description }}</span><span class="block text-xs text-zinc-400">{{ $activity->created_at->diffForHumans() }}</span></span></div>@empty<p class="py-6 text-sm text-zinc-500">No recent account activity.</p>@endforelse</div></section>
    </div>
</div>
