<div>
    @if(session('success'))<div class="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{{ session('success') }}</div>@endif
    <x-page-header :title="$document->name" :description="$document->project->name.' · Updated '.$document->updated_at->diffForHumans()">
        <x-status-badge :value="$document->visibility" /><flux:button icon="arrow-down-tray" :href="route('documents.download', $document)">Download</flux:button>
    </x-page-header>
    <div class="grid gap-6 xl:grid-cols-[1fr_360px]">
        <div class="space-y-6">
            <section class="overflow-hidden rounded-2xl border border-zinc-200 bg-white dark:border-zinc-800 dark:bg-zinc-900">
                <div class="border-b border-zinc-200 px-6 py-4 text-sm font-medium dark:border-zinc-800">Preview</div>
                <div class="grid min-h-[420px] place-items-center bg-zinc-50 p-8 dark:bg-zinc-950/50">
                    @if(str_starts_with($document->mime_type, 'image/'))<img src="{{ route('documents.preview', $document) }}" alt="{{ $document->name }}" class="max-h-[650px] rounded-lg object-contain">
                    @elseif($document->mime_type === 'application/pdf')<iframe src="{{ route('documents.preview', $document) }}" class="h-[650px] w-full rounded-lg" title="Document preview"></iframe>
                    @else<div class="text-center"><span class="mx-auto grid size-16 place-items-center rounded-2xl bg-white text-zinc-400 shadow-sm ring-1 ring-zinc-200 dark:bg-zinc-900 dark:ring-zinc-800"><flux:icon.document-text class="size-8" /></span><h3 class="mt-5 font-semibold">Preview isn’t available</h3><p class="mt-1 text-sm text-zinc-500">Download the original file to view its contents.</p><flux:button class="mt-5" variant="primary" icon="arrow-down-tray" :href="route('documents.download', $document)">Download {{ $document->original_filename }}</flux:button></div>@endif
                </div>
            </section>
            <section class="rounded-2xl border border-zinc-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900">
                <h2 class="font-semibold">Discussion <span class="text-zinc-400">{{ $document->comments->count() }}</span></h2>
                <form wire:submit="addComment" class="mt-5"><flux:textarea wire:model="comment" placeholder="Add a comment… Supports **bold**, *italic*, and [links](https://example.com)." rows="3" /><div class="mt-3 flex justify-end"><flux:button type="submit" variant="primary">Comment</flux:button></div></form>
                <div class="mt-7 space-y-6">@forelse($document->comments as $item)<div class="flex gap-3"><x-avatar :user="$item->user" /><div class="min-w-0 flex-1"><div class="flex items-center gap-2"><span class="text-sm font-medium">{{ $item->user->name }}</span><span class="text-xs text-zinc-400">{{ $item->created_at->diffForHumans() }}</span></div>@if($editingCommentId === $item->id)<form wire:submit="saveComment" class="mt-2"><flux:textarea wire:model="editingCommentBody" rows="3" /><div class="mt-2 flex gap-2"><flux:button type="submit" size="sm" variant="primary">Save</flux:button><flux:button wire:click="$set('editingCommentId', null)" size="sm">Cancel</flux:button></div></form>@else<div class="prose prose-sm mt-2 max-w-none text-zinc-700 dark:text-zinc-300">{!! $item->body_rendered !!}</div><div class="mt-2 flex gap-3">@can('update', $item)<button wire:click="beginEditComment({{ $item->id }})" class="text-xs text-zinc-500 hover:underline">Edit</button>@endcan @can('delete', $item)<button wire:click="deleteComment({{ $item->id }})" class="text-xs text-red-500 hover:underline">Delete</button>@endcan</div>@endif</div></div>@empty<p class="text-sm text-zinc-500">No comments yet. Start the conversation.</p>@endforelse</div>
            </section>
        </div>
        <aside class="space-y-6">
            <section class="rounded-2xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><h2 class="font-semibold">Details</h2><dl class="mt-5 space-y-4 text-sm"><div class="flex justify-between gap-4"><dt class="text-zinc-500">Owner</dt><dd class="font-medium">{{ $document->owner->name }}</dd></div><div class="flex justify-between"><dt class="text-zinc-500">Size</dt><dd>{{ $document->human_size }}</dd></div><div class="flex justify-between"><dt class="text-zinc-500">Type</dt><dd class="max-w-48 truncate">{{ $document->mime_type }}</dd></div><div class="flex justify-between"><dt class="text-zinc-500">Created</dt><dd>{{ $document->created_at->format('M j, Y') }}</dd></div></dl></section>
            @can('update', $document)<form wire:submit="saveDetails" class="rounded-2xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><h2 class="font-semibold">Document settings</h2><div class="mt-4 space-y-4"><flux:input wire:model="editName" label="Name" /><flux:textarea wire:model="editDescription" label="Description" rows="3" /><flux:select wire:model="editVisibility" label="Visibility"><flux:select.option value="project">Project</flux:select.option><flux:select.option value="private">Private</flux:select.option></flux:select></div><flux:button type="submit" variant="primary" class="mt-5 w-full">Save details</flux:button><flux:button wire:click="deleteDocument" wire:confirm="Delete this document?" type="button" variant="danger" class="mt-2 w-full">Delete document</flux:button></form>@endcan
            @can('share', $document)<section class="rounded-2xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><h2 class="font-semibold">Share access</h2><form wire:submit="shareWithUser" class="mt-4 space-y-3"><flux:input wire:model="shareEmail" type="email" placeholder="teammate@example.com" /><flux:select wire:model="sharePermission"><flux:select.option value="viewer">Can view</flux:select.option><flux:select.option value="editor">Can edit</flux:select.option></flux:select><flux:button type="submit" class="w-full">Share with user</flux:button></form>@if($document->shares->count())<div class="mt-4 space-y-3 border-t border-zinc-100 pt-4 dark:border-zinc-800">@foreach($document->shares as $share)<div class="flex items-center gap-2"><x-avatar :user="$share->user" size="size-7" /><span class="min-w-0 flex-1 truncate text-xs">{{ $share->user->name }}</span><x-status-badge :value="$share->permission" /><button wire:click="revokeShare({{ $share->id }})" class="text-xs text-red-500">Revoke</button></div>@endforeach</div>@endif</section>
            <section class="rounded-2xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><h2 class="font-semibold">Public links</h2><form wire:submit="generateLink" class="mt-4 space-y-3"><flux:input wire:model="linkExpiry" type="datetime-local" label="Optional expiry" /><flux:button type="submit" icon="link" class="w-full">Generate link</flux:button></form><div class="mt-4 space-y-3">@foreach($document->shareLinks as $link)<div class="rounded-lg bg-zinc-50 p-3 text-xs dark:bg-zinc-800"><div class="flex items-center justify-between gap-2"><span class="truncate font-mono">{{ $link->token }}</span>@if(!$link->revoked_at)<button wire:click="revokeLink({{ $link->id }})" class="text-red-500">Revoke</button>@endif</div><p class="mt-1 text-zinc-500">{{ $link->revoked_at ? 'Revoked' : ($link->expires_at ? 'Expires '.$link->expires_at->diffForHumans() : 'Never expires') }} · {{ $link->access_count }} views</p></div>@endforeach</div></section>@endcan
        </aside>
    </div>
</div>
